export const PlaceConstants = {
    GETPLACES_PROGRESS: 'PLACE_GETPLACES_PROGRESS',
    GETPLACES_SUCCESS: 'PLACE_GETPLACES_SUCCESS',
    GETPLACES_ERROR: 'PLACE_GETPLACES_ERROR',

    GETUSERPLACES_PROGRESS: 'PLACE_GETPLACES_BY_USER_PROGRESS',
    GETUSERPLACES_SUCCESS: 'PLACE_GETPLACES_BY_USER_SUCCESS',
    GETUSERPLACES_ERROR: 'PLACE_GETPLACES_BY_USER_ERROR',

    DELETEUSERPLACE_PROGRESS: 'PLACE_DELETEUSERPLACE_PROGRESS',
    DELETEUSERPLACE_SUCCESS: 'PLACE_DELETEUSERPLACE_SUCCESS',
    DELETEUSERPLACE_ERROR: 'PLACE_DELETEUSERPLACE_ERROR',

    SEARCHPLACE_PROGRESS: 'PLACE_SEARCHPLACE_PROGRESS',
    SEARCHPLACE_SUCCESS: 'PLACE_SEARCHPLACE_SUCCESS',
    SEARCHPLACE_ERROR: 'PLACE_SEARCHPLACE_ERROR',

    CREATEUSERPLACE_PROGRESS: 'PLACE_CREATEUSERPLACE_PROGRESS',
    CREATEUSERPLACE_SUCCESS: 'PLACE_CREATEUSERPLACE_SUCCESS',
    CREATEUSERPLACE_ERROR: 'PLACE_CREATEUSERPLACE_ERROR',

    INCREASEUSERPLACEPREFERENCE_PROGRESS: 'PLACE_INCREASEUSERPLACEPREFERENCE_PROGRESS',
    INCREASEUSERPLACEPREFERENCE_SUCCESS: 'PLACE_INCREASEUSERPLACEPREFERENCE_SUCCESS',
    INCREASEUSERPLACEPREFERENCE_ERROR: 'PLACE_INCREASEUSERPLACEPREFERENCE_ERROR',

    DECREASEUSERPLACEPREFERENCE_PROGRESS: 'PLACE_DECREASEUSERPLACEPREFERENCE_PROGRESS',
    DECREASEUSERPLACEPREFERENCE_SUCCESS: 'PLACE_DECREASEUSERPLACEPREFERENCE_SUCCESS',
    DECREASEUSERPLACEPREFERENCE_ERROR: 'PLACE_DECREASEUSERPLACEPREFERENCE_ERROR',

    UPDATE_USERPLACE_BATCH_PROGRESS: 'UPDATE_USERPLACE_BATCH_PROGRESS',
    UPDATE_USERPLACE_BATCH_SUCCESS: 'UPDATE_USERPLACE_BATCH_SUCCESS',
    UPDATE_USERPLACE_BATCH_ERROR: 'UPDATE_USERPLACE_BATCH_ERROR',
};