export const PlaceConstants = {
    GETPLACES_PROGRESS: 'PLACE_GETPLACES_PROGRESS',
    GETPLACES_SUCCESS: 'PLACE_GETPLACES_SUCCESS',
    GETPLACES_ERROR: 'PLACE_GETPLACES_ERROR',

    GETUSERPLACES_PROGRESS: 'PLACE_GETPLACES_BY_USER_PROGRESS',
    GETUSERPLACES_SUCCESS: 'PLACE_GETPLACES_BY_USER_SUCCESS',
    GETUSERPLACES_ERROR: 'PLACE_GETPLACES_BY_USER_ERROR',
};