export const SportConstants = {
    GETSPORTS_PROGRESS: 'SPORT_GETSPORTS_PROGRESS',
    GETSPORTS_SUCCESS: 'SPORT_GETSPORTS_SUCCESS',
    GETSPORTS_ERROR: 'SPORT_GETSPORTS_ERROR',

    GETUSERSPORTS_PROGRESS: 'SPORT_GETSPORTS_BY_USER_PROGRESS',
    GETUSERSPORTS_SUCCESS: 'SPORT_GETSPORTS_BY_USER_SUCCESS',
    GETUSERSPORTS_ERROR: 'SPORT_GETSPORTS_BY_USER_ERROR',
};