export const SportPlaceConstants = {
    CREATE_SPORTPLACE_ASSOCIATION_PROGRESS: 'CREATE_SPORTPLACE_ASSOCIATION_PROGRESS',
    CREATE_SPORTPLACE_ASSOCIATION_SUCCESS: 'CREATE_SPORTPLACE_ASSOCIATION_SUCCESS',
    CREATE_SPORTPLACE_ASSOCIATION_FAIL: 'CREATE_SPORTPLACE_ASSOCIATION_FAIL',
    
    READ_SPORTPLACE_ASSOCIATION_PROGRESS: 'READ_SPORTPLACE_ASSOCIATION_PROGRESS',
    READ_SPORTPLACE_ASSOCIATION_SUCCESS: 'READ_SPORTPLACE_ASSOCIATION_SUCCESS',
    READ_SPORTPLACE_ASSOCIATION_FAIL: 'READ_SPORTPLACE_ASSOCIATION_FAIL',

    UPDATE_SPORTPLACE_ASSOCIATION_PROGRESS: 'UPDATE_SPORTPLACE_ASSOCIATION_PROGRESS',
    UPDATE_SPORTPLACE_ASSOCIATION_SUCCESS: 'UPDATE_SPORTPLACE_ASSOCIATION_SUCCESS',
    UPDATE_SPORTPLACE_ASSOCIATION_FAIL: 'UPDATE_SPORTPLACE_ASSOCIATION_FAIL',

    DELETE_SPORTPLACE_ASSOCIATION_PROGRESS: 'DELETE_SPORTPLACE_ASSOCIATION_PROGRESS',
    DELETE_SPORTPLACE_ASSOCIATION_SUCCESS: 'DELETE_SPORTPLACE_ASSOCIATION_SUCCESS',
    DELETE_SPORTPLACE_ASSOCIATION_FAIL: 'DELETE_SPORTPLACE_ASSOCIATION_FAIL',
};