export const SportConstants = {
    GETSPORTS_PROGRESS: 'SPORT_GETSPORTS_PROGRESS',
    GETSPORTS_SUCCESS: 'SPORT_GETSPORTS_SUCCESS',
    GETSPORTS_ERROR: 'SPORT_GETSPORTS_ERROR',

    GETUSERSPORTS_PROGRESS: 'SPORT_GETSPORTS_BY_USER_PROGRESS',
    GETUSERSPORTS_SUCCESS: 'SPORT_GETSPORTS_BY_USER_SUCCESS',
    GETUSERSPORTS_ERROR: 'SPORT_GETSPORTS_BY_USER_ERROR',

    CREATE_USERSPORT_PROGRESS: 'CREATE_USERSPORT_PROGRESS',
    CREATE_USERSPORT_SUCCESS: 'CREATE_USERSPORT_SUCCESS',
    CREATE_USERSPORT_ERROR: 'CREATE_USERSPORT_ERROR',

    UPDATE_USERSPORT_BATCH_PROGRESS: 'UPDATE_USERSPORT_BATCH_PROGRESS',
    UPDATE_USERSPORT_BATCH_SUCCESS: 'UPDATE_USERSPORT_BATCH_SUCCESS',
    UPDATE_USERSPORT_BATCH_ERROR: 'UPDATE_USERSPORT_BATCH_ERROR',
};