export const UserConstants = {
    LOGIN_PROGRESS: 'USER_LOGIN_PROGRESS',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_ERROR: 'USER_LOGIN_ERROR',
    LOGOUT: 'USER_LOGOUT',

    REGISTER_PROGRESS: 'USER_REGISTER_PROGRESS',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_ERROR: 'USER_REGISTER_ERROR',
    
    ADD_USER_PROGRESS: 'ADD_USER_PROGRESS',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_ERROR: 'ADD_USER_ERROR',

};