export const UserConstants = {
    LOGIN_ERROR: 'USERS_LOGIN_ERROR',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGOUT: 'USERS_LOGOUT',
    LOGIN_PROGRESS: 'USERS_LOGIN_PROGRESS',
    ADD_USER_PROGRESS: 'ADD_USER_PROGRESS',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    ADD_USER_ERROR: 'ADD_USER_ERROR',

};