export const WeekendAdviceConstants = {
    WEEKENDADVICE_GET_SUCCESS: 'WEEKENDADVICE_GET_SUCCESS',
    WEEKENDADVICE_GET_PROGRESS: 'WEEKENDADVICE_GET_PROGRESS',
    WEEKENDADVICE_GET_ERROR: 'WEEKENDADVICE_GET_ERROR'
}