export const WeekendAdviceConstants = {
    WEEKENDADVICE_GET: 'WEEKENDADVICE_GET',
    WEEKENDADVICE_GET_PROGRESS: 'WEEKENDADVICE_GET_PROGRESS',
    WEEKENDADVICE_GET_ERROR: 'WEEKENDADVICE_GET_ERROR'
}