# 3 services :
# Client: NGINX + Wego SPA Application. The image is build.
# Server: Spring boot + wego Application. The image is build.
# Database: MySQL server. The image is pulled from a repository.
version: '3'
services:
  front:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile 
    image: 
      front
    depends_on:
      - apiserver
    container_name: 
      front
    ports:
      - "80:80"
  apiserver:
    build: 
      context: .
      dockerfile: ./docker/server/Dockerfile
    image: 
      apiserver
    container_name: 
      apiserver
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image:
      mysql:5.7.24
    container_name: 
      db  
    expose:
      - "3306"
    volumes:
      - /opt/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wego"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
