version: '3'

services:
  nginx:
    ports:
     - "8080:80"
  
  wego:
    build: .
  
  database:
    image: "mysql:5.7.23"
    volumes:
      - '/home/michel/mysql-data':'/var/lib/mysql'
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wego