# 3 services :
# Client: NGINX + Wego SPA Application. The image is build.
# Server: Spring boot + wego Application. The image is build.
# Database: MySQL server. The image is pulled from a repository.
version: '3'
services:
  front:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile 
    image: 
      front
    depends_on:
      - server
    container_name: 
      front
    ports:
      - "80:80"
    networks:
      - wego-network
  server:
    build: 
      context: .
      dockerfile: ./docker/server/Dockerfile
    image: 
      server
    depends_on:
      - mysql
    container_name: 
      server
    networks:
      - wego-network
  mysql:
    image:
      mysql:5.7.24
    container_name:
      mysql
    volumes:
      - /opt/mysql-data:/var/lib/mysql
    networks:
      - wego-network
    environment:
      MYSQL_DATABASE: "wego"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
networks: 
  wego-network: